# Generated by Django 4.1.7 on 2023-04-05 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300)),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "Mombasa"),
                            (2, "Kwale"),
                            (3, "Kilifi"),
                            (4, "Tana River"),
                            (5, "Lamu"),
                            (6, "Taita/Taveta"),
                            (7, "Garissa"),
                            (8, "Wajir"),
                            (9, "Mandera"),
                            (10, " Marsabit"),
                            (11, "Isiolo"),
                            (12, "Meru"),
                            (13, "Tharaka-Nithi"),
                            (14, "Embu"),
                            (15, "Kitui"),
                            (16, "Machakos"),
                            (17, "Makueni"),
                            (18, "Nyandarua"),
                            (19, "Nyeri"),
                            (20, "Kirinyaga"),
                            (21, "Murang'a"),
                            (22, "Kiambu"),
                            (23, "Turkana"),
                            (24, "West Pokot"),
                            (25, "Samburu"),
                            (26, "Trans Nzoia"),
                            (27, "Uasin Gishu"),
                            (28, "Elgeyo/Marakwet"),
                            (29, "Nandi"),
                            (30, "Baringo"),
                            (31, "Laikipia"),
                            (32, "Nakuru"),
                            (33, "Narok"),
                            (34, "Kajiado"),
                            (35, "Kericho"),
                            (36, "Bomet"),
                            (37, "Kakamega"),
                            (38, "Vihiga"),
                            (39, "Bungoma"),
                            (40, "Busia"),
                            (41, "Siaya"),
                            (42, "Kisumu"),
                            (43, "Homa Bay"),
                            (44, "Migori"),
                            (45, "Kisii"),
                            (46, "Nyamira"),
                            (47, "Nairobi City"),
                        ],
                        max_length=3,
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.TextField()),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
