# Generated by Django 4.1.7 on 2023-04-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
        migrations.RemoveField(model_name="user", name="county",),
        migrations.RemoveField(model_name="user", name="gender",),
        migrations.RemoveField(model_name="user", name="phone",),
    ]
