# Generated by Django 4.1.7 on 2023-04-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctoruser_patientuser_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="patientuser", name="user_ptr",),
        migrations.DeleteModel(name="DoctorUser",),
        migrations.DeleteModel(name="PatientUser",),
    ]
